### ISSUE TITLE
Limit does not work with nested cloning

### ISSUE THREAD

**Issue by razuro** [yapapaya/jquery-cloneya#11]
**How to replicate issue:**
1. Using the demo as example, put a limit, say **2**, on **Contact Information**
2. Clone the parent, do not clone contact information
3. You should be able to clone the contact information as many as you want in the 2nd parent (cloned parent)

And other issues if you play around with nested cloning & limit.

**Comment by yapapaya** [comment]
I've fixed this. The code that counts the clones was erraneous. The min and max counts were wrong and hence the clone and delete buttons failed. We'll have a proper release and documentation later.

**Comment by TheBigK** [comment]
@actual-saurabh - I can't seem to get this to work. Here's what I'm observing: -

GROUP A (

Clone XYZ [+] [-]

) [+] [-]  

Clone XYZ works fine and follows the limits. However, when Group A is cloned, the XYZ does not follow maximum limit and the delete button too becomes dysfunctional. Could you please point me to the minified file that has this bug fixed?
