### ISSUE TITLE
always clone "template"

### ISSUE THREAD

**Issue by mbi24** [yapapaya/jquery-cloneya#15]
Is it possible to clone always kind of template with one "outer" input and two "inner" inputs in nested mode?

After cloning inner form few times and then click to clone outer form, "new" outer form is cloned with one "outer" input and "inner" inputs cloned-few-times.

What I want to achieve is having one outer input and two inner inputs everytime I clone outer form, no matter how many "inner" inputs are.

Best regards,
Milosz

**Comment by yapapaya** [comment]
I've added a *preserveCount* option which is *false* by default. If you set it to true, if a clone had 2 children initially, all clones will have 2 children when they are created. I'll release it later.
