### ISSUE TITLE
Woking with other plugin

### ISSUE THREAD

**Issue by tranlamnhatnam** [yapapaya/jquery-cloneya#17]
I use **Cloneya** with  [Bootstrap-datetime-picker](http://eonasdan.github.io/bootstrap-datetimepicker/) but when clone new row datetime-picker work with only one input of row has been clone.

This is code in [jsbin](http://jsbin.com/paceyuroqo/1/edit?output)

![untitled](https://cloud.githubusercontent.com/assets/1934536/5756061/1c5fe1f0-9cde-11e4-92f0-28c93300eced.png)

**Comment by tranlamnhatnam** [comment]
Resolved with jquery ui datepicker

**Comment by razuro** [comment]
Did you solve that by re-initializing datepicker after creating clone?

**Comment by tugaytaskin** [comment]
I have the same issue, and tried to re-initializing the datepicker, but its not working:

```javascript
			.on('before_clone.cloneya', function(event, toClone)
			{
				toClone.find('select, .autocomplete').select2('destroy');

				toClone.find('.date').datepicker('remove');
			})
			.on('after_append.cloneya', function(event, toClone, newClone)
			{
				Helper.Select2( toClone.find('select') );

				Helper.Datepicker( toClone.find('.date') );

				Helper.Select2( newClone.find('select') );

				Helper.Datepicker( newClone.find('.date') );
			});
```

I am using the bootstrap-datepicker:
https://bootstrap-datepicker.readthedocs.org/en/latest/

**Comment by Rtransat** [comment]
Someone has a solution with [chosen](http://harvesthq.github.io/chosen/) plugin ?

**Comment by gchokeen** [comment]
I am sure it will work if you properly reinit the your external plugin on before_clone.cloneya, I you create the fiddle then it will be easy  to help you!

**Comment by Rtransat** [comment]
Found it ;)

```javascript
.on('before_clone.cloneya', function(event, toClone)
{
    toClone.find('select').each(function()
    {
        $(this).chosen('destroy');
    });
})
.on('after_clone.cloneya', function (event, toClone, newclone) {
    toClone.find('select').each(function()
    {
        $(this).chosen();
    });
})
.on('after_append.cloneya', function (event, toClone, newclone) {
    newclone.find('select').each(function()
    {
        $(this).chosen();
    });
```

**Comment by adisuwarso** [comment]
Hi,

Thanks for code samples in jQuery-Chosen, that works like a charm.
I would ask about Bootstrap-Datepicker and Bootstrap-Timepicker?

In my case seems to be not work properly, after clone process daterangepicker turned into datepicker, I can change the date in enddate becomes smaller than startdate.

And for my case in Bootstrap-Timepicker, i could not applying the right command to make the cloning result works well.

Here is my code :

.on('before_clone.cloneya', function (event, toClone) {
  toClone.find('input.daterange_picker').each(function() {
    $(this).datepicker('remove');
  });
  toClone.find('input.time_picker').each(function() {
    $(this).timepicker('remove');
  });
})
.on('after_clone.cloneya', function (event, toClone, newclone) {
  toClone.find('input.daterange_picker').each(function() {
    $(this).datepicker({
      startDate: date,
      autoclose: true,
      format: 'yyyy-mm-dd',
      todayHighlight: true,
    });
  });
  toClone.find('input.time_picker').each(function() {
    $(this).timepicker({
      minuteStep : 5,
      showMeridian : false,
      showInputs : false
    });
  });
})
.on('before_append.cloneya', function (event, toClone, newclone) {
  $(newclone).css('display', 'none');
  $(toClone).fadeOut('fast', function () {
    $(this).fadeIn('fast');
  });
  toClone.find('input.daterange_picker').each(function() {
    $(this).datepicker({
      startDate: date,
      autoclose: true,
      format: 'yyyy-mm-dd',
      todayHighlight: true,
    });
  });
  toClone.find('input.time_picker').each(function() {
    $(this).timepicker({
      minuteStep : 5,
      showMeridian : false,
      showInputs : false
    });
  });
})
.on('after_append.cloneya', function (event, toClone, newclone) {
  $(newclone).slideToggle();
  console.log('finished cloning ' + toClone.attr('id') + ' to ' + newclone.attr('id'));
  newclone.find('input.daterange_picker').each(function() {
    $(this).datepicker({
      startDate: date,
      autoclose: true,
      format: 'yyyy-mm-dd',
      todayHighlight: true,
    });
  });
  newclone.find('input.time_picker').each(function() {
    $(this).timepicker({
      minuteStep : 5,
      showMeridian : false,
      showInputs : false
    });
  });
})

Realy appreciate if someone can help my for this.

And this the result examples :
![daterange_and_time_picker](https://cloud.githubusercontent.com/assets/16206072/12484678/f5c50730-c08d-11e5-9a7a-d51bdd5dc831.png)
