### ISSUE TITLE
Will this work in jQuery 1.5 version?

### ISSUE THREAD

**Issue by sakthiemail** [yapapaya/jquery-cloneya#19]
Will this work in jQuery version 1.5?
I also noticed the following errors in IE7 & IE8.

" SCRIPT5009: 'jQuery' is undefined 
 jquery-cloneya.js, line 8 character 1
 SCRIPT5007: The value of the property '$' is null or undefined, not a Function object 
 demo, line 107 character 13 "

Thanks.

**Comment by gchokeen** [comment]
Thanks for giving attention on it, Plugin supports **jQuery >=1.7**. I updated the dependencies in required files
