### ISSUE TITLE
Create more than one inner form in single form

### ISSUE THREAD

**Issue by sakthiemail** [yapapaya/jquery-cloneya#20]
Thank you for great jQuery-cloneya plugin.
How can we create more than one inner form within the main form.
I am using one main form with four inner forms.
The fresh main form worked perfectly with all the inner forms.
After cloning of the main form,did not display all the inner forms.
 It display first inner form only.
Any help will be appreciated.

Thanks,

**Comment by gchokeen** [comment]
Why don't you create jsfiddle or something for easy understanding

**Comment by sakthiemail** [comment]
http://jsfiddle.net/f6yLw8ch/11/

I created my form in above jsfiddle url
It worked with firefox only.
please check give me a sugesstion for me.
is it right or wrong?

**Comment by yapapaya** [comment]
The js fiddle wouldn't work because you used the raw.github.com. With strict mime type checking it is blocked. You would need to use the one from github pages: http://yapapaya.github.io/jquery-cloneya/javascripts/jquery-cloneya.min.js

See this updated fiddle where things seem to work fine: http://jsfiddle.net/f6yLw8ch/13/

**Comment by sakthiemail** [comment]
Thank you for your reply.
It is working. I will implement.
How can I add form validation for cloned form.
Please,Can you explain.

**Comment by gchokeen** [comment]
@sakthiemail : what you mean by validation. I usually do [jquery validation](http://jqueryvalidation.org/) with cloned form. you can find more relavent question and solusions in Stackoverflow. If you don't find raise one specific question in So with jquery-cloneya tag!
