### ISSUE TITLE
Delete all clones

### ISSUE THREAD

**Issue by blaskxx** [yapapaya/jquery-cloneya#22]
how do i limit the times of deleting? because with your example it delete me all the form

**Comment by gchokeen** [comment]
Which example you checked, I unable to reproduce it, What is the steps to reproduce it.

**Comment by yapapaya** [comment]
@blaskxx I guess, you need a minimum count. This is not present in cloneya, but we'll add it in 1.0. See #25

**Comment by yapapaya** [comment]
@blaskxx we've added a *minimum* parameter and modified the deletion. Could you test and see if this one fixes your issue? We'll be releasing 1.0 soon.

**Comment by blaskxx** [comment]
Thanks great job!

**Comment by yapapaya** [comment]
I have just released it. I'm closing the issue. If you still face a problem, we'll reopen this ticket.
