### ISSUE TITLE
Any hook is there to restrict the add/append clonned form for validation purpose?

### ISSUE THREAD

**Issue by sakthiemail** [yapapaya/jquery-cloneya#23]
I want to validate the form before cloning.
I do not need to append/add clonedform before validating the actual form.
is any other hooks available in jquery-cloneya plugin. Please give some suggestion.

**Comment by yapapaya** [comment]
There are a lot of events that you can hook on to. Did you see the readme: https://github.com/yapapaya/jquery-cloneya#specific-events ?
