### ISSUE TITLE
defaultCount

### ISSUE THREAD

**Issue by yapapaya** [yapapaya/jquery-cloneya#33]
@gchokeen With nesting, `defaultCount` produces weird results, which are logical but may not be expected by the user.

I'm not sure if we need `defaultCount` because I believe rendering can be done better by the server side scripting or plain copy paste html. I'm in huge favour of removing defaultCount. 

Do you have any use case where this parameter is required and makes life easier? Let me know your thoughts.

**Comment by yapapaya** [comment]
Especially since this could easily be done by the following code, if at all necessary:

```javascript
defaultCount = 5; //for eg.
$clonewrap.cloneya();
$toclone = $( 'some-selector-to-clone' );

for ( var i = 0; i < defaultCount; i++ ){
     $clonewrap.triggerHandler( 'clone.cloneya',  [$toclone] );
}
```

**Comment by gchokeen** [comment]
Okay, Let's go for that since it's easy to do from user end. Let's put in wiki.

**Comment by gchokeen** [comment]
defaultCount option removed since v1.0.0
