### ISSUE TITLE
Why child-selector?

### ISSUE THREAD

**Issue by gchokeen** [yapapaya/jquery-cloneya#37]
In the lastest plugin release 1.0.0, cloneya using [child-selector](http://www.w3.org/TR/CSS21/selector.html#child-selectors) for all the delete & clone button. It making us to use strict & standard structure, is it really required?

When I work accross the bootstrap form, I faced problem below structure 

```
          <div class="clone-wrapper">
         <div class="input-group form-group toclone">
              <input type="text" class="form-control" id="field_label" placeholder="Field Label">  
              <div class="input-group-addon"><a href="javascript:void(0);" class="clone"><i class="glyphicon glyphicon-plus"></i></a></div>
      </div>
      </div>
```
This one solved 
```
<div class="input-group-addon clone"><a href="javascript:void(0);"><i class="glyphicon glyphicon-plus"></i></a></div>
```
Do you think it's really important to do that!

**Comment by chrisvanderpoel** [comment]
@gchokeen You can actually do this by simply specifying the CSS selector route down to the `.clone` element.  As you can see [in the source](https://github.com/yapapaya/jquery-cloneya/blob/stable/dist/jquery-cloneya.js#L123), it's just appended to the `toClone` selector.  So you can do something like:

```javascript
$('.clone-wrapper').cloneya({
    cloneButton: 'div.card > div.card-head > div.tools > div.btn-group > a.clone'
})
```

**Comment by gchokeen** [comment]
Yep, that's extra effort, but it still make sense!
