### ISSUE TITLE
nested elements of a clone cannot be deleted

### ISSUE THREAD

**Issue by danderson421** [yapapaya/jquery-cloneya#41]
in your nested demo, if you add phone numbers, then clone the contact, the phone numbers in the cloned contact cannot be deleted. not related to my implementation, not working on your demo page either. Otherwise, great work... would love to have this issue resolved if possible.

**Comment by gchokeen** [comment]
I checked it's clearing the phone number filed on the [demo](http://yapapaya.github.io/jquery-cloneya/demo.html)

**Comment by danderson421** [comment]
I checked again... it clears the phone on the original element, but not if it's cloned.

**Comment by lagunawebdesign** [comment]
For me 'DELETE' button it doesn't work too after cloning... - any solution?

**Comment by TheBigK** [comment]
I'm looking for the solution as well. The delete button does not work when group is cloned.

**Comment by actual-saurabh** [comment]
@danderson421 @lagunawebdesign @TheBigK yes, this is a bug. The clones of the children of cloned elements can't be deleted. I'll need to write some unit test cases and debug this. This will take a little while.

**Comment by TheBigK** [comment]
@actual-saurabh - Thanks! I was pulling out my hair over this. Would really be thankful if you could fix this. I'm using it in a project that'd be super awesome if this gets fixed.

**Comment by TheBigK** [comment]
Awesome. @actual-saurabh - Does this also fix the bug that childs do not respect 'maximum' setting?

**Comment by actual-saurabh** [comment]
Yes. The problem was that it was not able to count the total number of existing sibling clones because of a bug. It always used to come to 0. That is why it wasn't getting deleted or respecting the maximum count, because it'd never reach the maximum count.

**Comment by TheBigK** [comment]
Can't thank you enough man. Coffee on me if we meet in Pune. That said, I really need help with a problem about applying selectors to the child items. Would really appreciate if you could help with it. I've tweeted the link to you.
