### ISSUE TITLE
How do I make the input names increase incrementally?

### ISSUE THREAD

**Issue by BenComicGraphics** [yapapaya/jquery-cloneya#44]
I'm using this, and I need a way to ensure the input names increase like the ID's are.

**Comment by gchokeen** [comment]
Cloneya already handlng it, You need to set field name as array ```<input type="text" name="name[1]"/>```. Cloneya will automatically increment the numeric index of array.

**Comment by BenComicGraphics** [comment]
Got it! tHX!

**Comment by girlscancode** [comment]
Hi gchokeen, 

OK, I think this is not working - and I am looking at the actual demo page you have set up, the name field is not automatically incremented

Best, 
Gabriela

**Comment by acoulton** [comment]
You also need to set the (undocumented) config option `serializeIndex` to true to make it work. Note also that currently if you have more than one numeric bit in your fieldname cloneya will reset *all* of them to the clone index (see #42)

**Comment by girlscancode** [comment]
Aaah, ok, I see! Thanks Andrew!

**Comment by shibin-pb** [comment]
serializeIndex is not incrementing properly and it stops the numeric indexing of input array at 10 when clone count becomes more than 10 

`<input type="text" name="name[0]"/>
<input type="text" name="name[1]"/>
<input type="text" name="name[2]"/>
<input type="text" name="name[3]"/>
<input type="text" name="name[4]"/>
<input type="text" name="name[5]"/>
<input type="text" name="name[6]"/>
<input type="text" name="name[7]"/>
<input type="text" name="name[8]"/>
<input type="text" name="name[9]"/>
<input type="text" name="name[10]"/>
<input type="text" name="name[10]"/>
<input type="text" name="name[10]"/>`
