### ISSUE TITLE
how to remove a class from all children of the cloned elemnt ?

### ISSUE THREAD

**Issue by quasiperfect** [yapapaya/jquery-cloneya#47]
hi

please answer the question from the title.
thanks in advance

**Comment by actual-saurabh** [comment]
Please use the `after_clone` event: https://github.com/yapapaya/jquery-cloneya/wiki/Events#after_clone or the `before_append` event: https://github.com/yapapaya/jquery-cloneya/wiki/Events#before_append to manipulate the cloned element.
