### ISSUE TITLE
Nested child incrementing the parent name

### ISSUE THREAD

**Issue by absmugz** [yapapaya/jquery-cloneya#53]
I have a challenge were I have a nested form and the nested form must have children, but when I try to add the child form in incrementing the parent name 

`<div class="nest-clone inner-wrap">
                        <div class="toclone">
                            <strong>Questions</strong>
                            <p class="ques"> 
                                <input type="text" name="question[0][ques]" /> 
                                <label for="ques">Set Question</label> 
                            </p> 
                            
                            <p class="ans"> 
                                <input type="text" name="question[0][ans]" /> 
                                <label for="ans">Correct Answer</label> 
                            </p>

                            <p class="ansInfo"> 
                                <input type="text" name="question[0][ansInfo]" /> 
                                <label for="ansInfo">answer Info</label> 
                            </p>
                            
 <div class="nest-clone inner-inner-wrap">
                                <div class="toclone">
                                    <strong>Answer option</strong>
                                    <p class="ansSel">
                                  
                                        <input type="text" name="question[0][ansSel]" /> 
                                        <label for="ansSel">option</label> 
                                    </p>  
                                    <a href="#" class="clone">clone</a>
                                    <a href="#" class="delete">delete</a>
                                </div>
                            </div>
                            

                              
                           
                            <a href="#" class="clone">clone</a>
                            <a href="#" class="delete">delete</a>
                        </div>
                    </div>
                    
                </div>

                <p class="submit"> 
                    <input type="submit" value="Save" /> 
                </p> 

            </form>`

I want to get data like this -

question[0][ques]
question[0][ans]
question[0][ansInfo]

The above part works but now for the nested I want this -

question[0][ansSel][0]
question[0][ansSel]1]
question[0][ansSel][2]
question[0][ansSel][3]

But when I click the clone button for the nested child form it does this - 

question[1][ansSel]
question[2][ansSel]
question[3][ansSel]
question[4][ansSel]

**Comment by actual-saurabh** [comment]
Hey @absmugz, 

You should use the `after_clone` and `before_append` events (https://github.com/yapapaya/jquery-cloneya/wiki/Events#after_clone) to manage this on your own. Cloneya cannot manage this sensibly for the numerous use cases.

**Comment by actual-saurabh** [comment]
Also see #42

**Comment by akhildasop** [comment]
hai @actual-saurabh,

 worked with  '"after_clone" and "before_append" events. but still we didnt received the desired namings.

how to get the serialized index in clone ?
