### ISSUE TITLE
Auto increment on a multi dimensional PHP sstsy

### ISSUE THREAD

**Issue by ghost** [yapapaya/jquery-cloneya#6]
Hi

There is a small issue when cloning form elements that have a PHP multi dimmensional array scheme, for example if I had a fieldset with 3 fields which I wanted to clone, its not renumbering the array correctly, to give an example, if I loaded a form for editing which was pre-populated with 2 sets of information

contact[0][name]
contact[0][address]
contact[0][phone]

contact[1][name]
contact[1][address]
contact[1][phone]

Then I clicked clone/add another copy of the fieldset, I'd expect the array to renumbered as 

contact[0][name]
contact[0][address]
contact[0][phone]

contact[1][name]
contact[1][address]
contact[1][phone]

contact[2][name]
contact[2][address]
contact[2][phone]

Instead, the first array element number is being cleared from the first set, so we end up with

contact[][name]
contact[][address]
contact[][phone]

contact[1][name]
contact[1][address]
contact[1][phone]

contact[2][name]
contact[2][address]
contact[2][phone]

This is possible by design, but we tracked the issue down to the "j" being unset on line 212, commenting out this if statement fixed the issue for us. But perhaps you could make this behaviour optional. 

Many Thanks

**Comment by Rtransat** [comment]
It's possible to reset index ?

For example:

contact[0][name]
contact[0][address]
contact[0][phone]

contact[1][name]
contact[1][address]
contact[1][phone]

contact[2][name]
contact[2][address]
contact[2][phone]

If I delete index 0. 1 becomes 0 and 2 becomes 1 ?
